### PR TITLE
Update Haml-Lint dependency

### PR DESCRIPTION
**Pull request by michaelherold**
We have made some large changes to the `haml_lint` gem that caused some
incompatibilities in `pronto-haml`. In order to deal with these issues,
I updated to the version recommendation for `haml_lint` to a newer
version and updated the wrapper to use the new structure.

Closes brigade/haml-lint#197

### CODE REVIEW

**Comment by michaelherold** [comment]
Hmm ... the tests are failing on Travis. That's odd. I'll look into it.

Also, we require Ruby 2.1+ for modern Haml-Lint. That's why Ruby 2.0 is failing.

**Comment by michaelherold** [comment]
The build is now passing. I removed Ruby 2.0 from the Travis configuration in a separate commit. Hopefully, that's acceptable given that haml-lint requires Ruby 2.1+.

Please let me know if there's anything else you need for this!

**Comment by mmozuras** [comment]
@michaelherold thanks, that's perfect! 🙇

**Comment by mmozuras** [comment]
Released as [v0.8.1](https://github.com/mmozuras/pronto-haml/releases/tag/v0.8.1).

**Pull request merged**
